version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/todolist
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
